# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'svc-sonar'
    scannerMode: 'Other'
    extraProperties: 'sonar.projectKey=YourProjectKey'


- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'